export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const INSERT_MONEY = "INSERT_MONEY";

export const SHOW_ERROR = "SHOW_ERROR";

export const BUY_PRODUCT_REQUEST = "BUY_PRODUCT_REQUEST";
export const BUY_PRODUCT_SUCCESS = "BUY_PRODUCT_SUCCESS";
export const BUY_PRODUCT_FAILURE = "BUY_PRODUCT_FAILURE";

export const BUY_LAST_PRODUCT_REQUEST = "BUY_LAST_PRODUCT_REQUEST";
export const BUY_LAST_PRODUCT_SUCCESS = "BUY_LAST_PRODUCT_SUCCESS";
export const BUY_LAST_PRODUCT_FAILURE = "BUY_LAST_PRODUCT_FAILURE";

export const GIVE_CHANGE = "GIVE_CHANGE";
